Lab-3/Home/urls.py
from django.urls import path
from .views import *

app_name = 'BookStore'

urlpatterns = [
    path('',  index, name="book-index"),
    path("books/create", create, name="book-create"),
    path("books/store", store, name="book-store"),
    path("books/<int:id>", show, name="book-show"),
    path("books/<int:id>/delete", destroy, name="book-delete"),
    path("books/<int:id>/update", update, name="book-update"),
    path("books/<int:id>/edit", edit, name="book-edit")

]

Lab-3/bookStore/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path("user/" , include('user.urls') , name="user")
]

Lab-3/user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login" , views.user_login , name="login"),
    path("logout" , views.user_logout , name="logout"),
    path("signup" , views.user_signup , name="signup"),
]

Lab-3/Home/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
import uuid
from django.core.exceptions import ValidationError


class Isbn(models.Model):
    author_title = models.CharField(max_length=30)
    book_title = models.CharField(max_length=30)
    isbn = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    def __str__(self):
        return self.author_title


class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name
    def clean(self) -> None:
        if len(self.name) < 2:
            raise ValidationError('Category name must be more than 2 characters')
        return super().clean()


class Book(models.Model):
    author_name = models.CharField(max_length=30)
    genre = models.CharField(max_length=15)
    title = models.CharField(max_length=50,unique=True)
    description = models.TextField()
    rate = models.IntegerField()
    views = models.IntegerField()
    slug = models.SlugField(unique=True, max_length=255, blank=True , editable=False)
    user = models.ForeignKey(User , on_delete=models.PROTECT)
    isbn = models.OneToOneField(Isbn , on_delete=models.CASCADE)
    category = models.ManyToManyField(Category)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Book, self).save(*args, **kwargs)

    def __str__(self):
        return self.author_name

    def clean(self):
        if len(self.title) < 10:
            raise ValidationError("Title must be more than 10 characters")
        return super().clean()

Lab-3/user/models.py
from django.db import models

# Create your models here.

Lab-3/user/forms.py
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth.models import User
from django import forms


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})),

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username' , 'first_name' , 'last_name' , 'email']

Lab-3/Home/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect
from Home.models import Book
from .form import BookForm
from django.contrib.auth.decorators import login_required

@login_required(login_url='/user/login')
def index(request):
    books = Book.objects.all().values()
    return render(request, "home/index.html", {"books": books})

@login_required(login_url='/user/login')
def show(request, id):
    book = Book.objects.get(pk=id)
    return render(request, "home/show.html", {"book": book})

@login_required(login_url='/user/login')
def edit(request, id):

    book = Book.objects.get(pk=id)
    form = BookForm(instance=book)
    return render(request, "home/edit.html", {'form':form , 'book':book})

@login_required(login_url='/user/login')
def create(request):

    form = BookForm()
    return render(request, "home/create.html" , {"form" : form})

@login_required(login_url='/user/login')
def store(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            book = form.save(commit=False)
            book.user = request.user  # Assign the current user to the book
            book.save()
            return redirect('BookStore:book-index')
        else:
            print(form.errors)
    else:
        form = BookForm()
    return render(request, "home/create.html", {"form": form})

@login_required(login_url='/user/login')
@csrf_protect
def update(request, id):
    book = Book.objects.get(pk=id)
    form = BookForm(request.POST, instance=book)
    if form.is_valid():  # Call is_valid() as a function
        form.save()

    return redirect("BookStore:book-index")



@login_required(login_url='/user/login')
def destroy(request, id):

    book = Book.objects.get(pk=id)
    book.delete()
    return redirect("BookStore:book-index")

Lab-3/user/views.py
from django.shortcuts import render , redirect
from django.contrib import messages
from django.contrib.auth import login , logout , authenticate
from .forms import LoginForm , SignUpForm


def user_login(request):
    form = LoginForm()
    if request.user.is_authenticated:
        return redirect("BookStore:book-index")

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is None:
            return render(request, "accounts/login.html", {"form": form})
        login(request , user)
        return redirect("BookStore:book-index")
    else:
        return render(request, "accounts/login.html" , {"form": form})


def user_logout(request):
    logout(request)
    return redirect("user:login")


def user_signup(request):
    form = SignUpForm()
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect("user:login")
        else:
           errors = form.errors
           return render(request, "accounts/signup.html" , {"form": form , "errors": errors})
    else:
        return render(request, "accounts/signup.html" , {"form": form})

Lab-3/Home/templates/home/create.html
{% extends 'main/base_layout.html' %}
{% load static %}

{% block title %}Create New Book{% endblock %}

{% block main-content %}

<div class="container mx-auto px-4">
    <form class="max-w-md mx-auto bg-white p-8 rounded shadow-md" id="form-edit" method="POST" action="{% url 'BookStore:book-store' %}">
        <div class="text-2xl font-semibold mb-6">Add New Book</div>
        {% csrf_token %} {% for field in form %}
        <div class="mb-4">
            {% if field.errors %}
            <div class="text-red-500 text-sm mb-2">
                {% for error in field.errors %}
                {{ error }}
                {% endfor %}
            </div>
            {% endif %}
            <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            <div class="w-full bg-white border border-gray-300 rounded-md py-2 px-3">
                {{ field }}

            </div>


        </div>
        {% endfor %}
        <button type="submit" class="w-full bg-indigo-500 text-white py-2 px-4 rounded hover:bg-indigo-600 transition duration-300">Save</button>
    </form>
</div>

{% endblock %}

Lab-3/Home/templates/home/edit.html
{% extends 'main/base_layout.html' %}
{% load static %}

{% block title %}Create New Book{% endblock %}

{% block main-content %}

<div class="container mx-auto">
    <form class="max-w-md mx-auto bg-white p-8 rounded shadow-md" id="form-edit" method="POST" action="{% url 'BookStore:book-update' book.id  %}">
        <div class="text-2xl font-semibold mb-6">Update a Book</div>
        {% csrf_token %}
        <div class="mb-4 shadow-md">
            <label for="id_title" class="block text-gray-700 text-sm font-bold mb-2">Title:</label>
            {{ form.title }}
        </div>
        <div class="mb-4 shadow-md">
            <label for="id_author_name" class="block text-gray-700 text-sm font-bold mb-2">Author Name:</label>
            {{ form.author_name }}
        </div>
        <div class="mb-4 shadow-md">
            <label for="id_genre" class="block text-gray-700 text-sm font-bold mb-2">Genre:</label>
            {{ form.genre }}
        </div>
        <div class="mb-4 shadow-md">
            <label for="id_description" class="block text-gray-700 text-sm font-bold mb-2">Description:</label>
            {{ form.description }}
        </div>
        <div class="mb-4 shadow-md">
            <label for="id_rate" class="block text-gray-700 text-sm font-bold mb-2">Rate:</label>
            {{ form.rate }}
        </div>
        <div class="mb-4 shadow-md">
            <label for="id_views" class="block text-gray-700 text-sm font-bold mb-2">Views:</label>
            {{ form.views }}
        </div>
        <button type="submit" class="w-full bg-indigo-500 text-white py-2 px-4 rounded hover:bg-indigo-600 transition duration-300 shadow-md">Update</button>
    </form>
</div>

{% endblock %}

Lab-3/Home/templates/home/index.html
{% extends 'main/base_layout.html' %}

{# override block title #}
{% block title %}
    Books List
{% endblock %}

{# override body #}
{% block main-content %}
<div class="container mx-auto" style="min-height: 90vh;">
    <div>
        <div class="flex justify-end items-center my-4">
            <a class="bg-green-500 text-white px-4 py-2 rounded shadow-md hover:bg-green-600 transition duration-300" href="{% url 'BookStore:book-create' %}">Add New Book</a>
        </div>

        <table class="table-auto text-center mx-auto rounded-md">
            <thead>
                <tr>
                    <th scope="col" class="px-4 py-2">ID</th>
                    <th scope="col" class="px-4 py-2">Author</th>
                    <th scope="col" class="px-4 py-2">Title</th>
                    <th scope="col" class="px-4 py-2">Desc.</th>
                    <th scope="col" class="px-4 py-2">Type</th>
                    <th scope="col" class="px-4 py-2">Rate</th>
                    <th scope="col" class="px-4 py-2">Views</th>
                    <th scope="col" class="px-4 py-2">Action</th>
                </tr>
            </thead>

            <tbody>
                {% for book in books %}
                <tr>
                    <td class="border px-4 py-2 rounded-md">{{book.id}}</td>
                    <td class="border px-4 py-2 rounded-md">{{book.author_name}}</td>
                    <td class="border px-4 py-2 rounded-md">{{book.title}}</td>
                    <td class="border px-4 py-2 rounded-md">{{ book.description | truncatewords:2 | title }}</td>
                    <td class="border px-4 py-2 rounded-md">{{book.genre}}</td>
                    <td class="border px-4 py-2 rounded-md">{{book.rate}}</td>
                    <td class="border px-4 py-2 rounded-md">{{book.views}}</td>
                    <td class="border px-4 py-2 rounded-md">
                        <a class="bg-blue-500 text-white px-4 py-2 rounded shadow-md hover:bg-blue-600 transition duration-300 mr-2" href="{% url 'BookStore:book-show' book.id %}"> View</a>
                        <a class="bg-red-500 text-white px-4 py-2 rounded shadow-md hover:bg-red-600 transition duration-300 mr-2" href="{% url 'BookStore:book-delete' book.id %}"> Delete</a>
                        <a class="bg-indigo-500 text-white px-4 py-2 rounded shadow-md hover:bg-indigo-600 transition duration-300" href="{% url 'BookStore:book-edit' book.id %}"> Update</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="8" class="border px-4 py-2 rounded-md text-center"> Sorry, This Book Not Found in The List</td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
</div>
{% endblock %}

Lab-3/Home/templates/home/show.html
{% extends 'main/base_layout.html' %}
{% block main-content %}
<div class="container mx-auto flex flex-col justify-center items-center" style="min-height: 80vh;">
  <h2 class="text-center font-semibold text-3xl mb-6 text-indigo-500">Welcome to Book Details of: {{book.title}}</h2>
  <div class="flex justify-center mt-3 p-2">
    <div class="bg-white rounded-lg shadow-md p-6">
      <h5 class="text-lg font-bold mb-4 text-indigo-500">
        Book Title: <span class="text-gray-800">{{ book.title }}</span>
      </h5>
      <p class="text-lg mb-2 text-indigo-500 font-bold">
        Book ID: <span class="text-gray-800">{{ book.id }}</span>
      </p>
      <p class="text-lg mb-2 text-indigo-500 font-bold">
        Book Author: <span class="text-gray-800">{{ book.author_name }}</span>
      </p>
      <p class="text-lg mb-2 text-indigo-500 font-bold">
        Book Description: <span class="text-gray-800">{{ book.description }}</span>
      </p>
      <p class="text-lg mb-2 text-indigo-500 font-bold">
        Book Type: <span class="text-gray-800">{{ book.type }}</span>
      </p>
      <p class="text-lg mb-2 text-indigo-500 font-bold">
        Book Rate: <span class="text-gray-800">{{ book.rate }}</span>
      </p>
      <p class="text-lg mb-2 text-indigo-500 font-bold">
        Book Views: <span class="text-gray-800">{{ book.views }}</span>
      </p>
      <p class="text-lg mb-2 text-indigo-500 font-bold">
        Book User: <span class="text-gray-800">{{ book.user }}</span>
      </p>
      <p class="text-lg mb-2 text-indigo-500 font-bold">
        Book ISBN: <span class="text-gray-800">{{ book.isbn }}</span>
      </p>
      {% for category in book.category.all %}
      <p class="text-lg mb-2 text-indigo-500 font-bold">
        Book Category: <span class="text-gray-800">{{ category.name }}</span>
      </p>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}